"""Pydantic request/response shapes. Kept separate from ORM so API changes stay explicit."""

import uuid
from datetime import datetime

from pydantic import BaseModel, Field


class ProductCreate(BaseModel):
    """Body for creating a product; stock is an integer count of remaining units."""

    name: str = Field(min_length=1, max_length=255)
    stock: int = Field(ge=0)
    price_cents: int = Field(ge=0)


class ProductOut(BaseModel):
    """Public product view, including live stock after reservations."""

    id: uuid.UUID
    name: str
    stock: int
    price_cents: int

    model_config = {"from_attributes": True}


class CheckoutRequest(BaseModel):
    """Start a reservation.

    `idempotency_key` is generated by the client (typically a UUID per tap of
    the buy button). Sending the same key again must return the same order
    instead of taking another unit — phones retry after timeouts.

    `admission_token` is issued by the waiting room after drip-feed admission.
    Production traffic must present a live token so checkout volume stays
    bounded. Tests/scripts may omit it only with the internal bypass header.
    """

    product_id: uuid.UUID
    buyer_id: str = Field(min_length=1, max_length=255)
    idempotency_key: str = Field(min_length=1, max_length=255)
    admission_token: str | None = None


class WaitingRoomJoinRequest(BaseModel):
    """Identity of the person taking a number for a specific SKU."""

    product_id: uuid.UUID
    buyer_id: str = Field(min_length=1, max_length=255)


class WaitingRoomStatusOut(BaseModel):
    """What a polling client needs: place in line, or the token to checkout."""

    ticket_id: uuid.UUID
    product_id: str
    buyer_id: str
    position: int | None = None
    admitted: bool
    admission_token: str | None = None
    admission_expired: bool = False


class OrderOut(BaseModel):
    """What the client needs to confirm payment or show reservation state."""

    id: uuid.UUID
    product_id: uuid.UUID
    buyer_id: str
    status: str
    idempotency_key: str
    expires_at: datetime
    created_at: datetime

    model_config = {"from_attributes": True}
